# Site settings
url: "http://www.viajandonasferias.com.br"
title: Viajando nas férias
description: > # > serve pra ignorar line brake até a proxima opcao
  Dicas e compartilhamento de nossas experiencias de viagens, permitindo trocar
  conhecimentos sobre roteiros, ajudando pessoas a organizar suas viagens sozinhas.

# Build settings
markdown: kramdown
highlighter: rouge
timezone: "America/Sao_Paulo"
permalink: /:categories/:title
host: 0.0.0.0
port: 3000
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

# Amount of post to show on home page
paginate: 6

include: 
  - .htaccess
exclude: 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp